/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastanekayitsistemi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABRA
 */
public class HastaRandevu extends javax.swing.JFrame {
    
    static final String DB_URL = "jdbc:mysql://localhost:3306/hastane?serverTimezone=UTC";
    static final String USER = "root";
    static final String PASS = "";
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(DB_URL,USER,PASS);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Sayfa1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Hata Burada 1");
        } catch (SQLException ex) {
            Logger.getLogger(Sayfa1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Hata Burada 2");
        }
        
    }
    private String ad,soyad,ünvan;
    public void LoadDoctor(){
        try {
            String poli= txtpoliklinik.getSelectedItem().toString();
            pst = con.prepareStatement("select * from doktor where poliklinik = ?");
            pst.setString(1, poli);
            rs = pst.executeQuery();
            txtdoktor.removeAll();
            
            while(rs.next()){
                ad = rs.getString("doktor_isim");
                soyad = rs.getString("doktor_soyisim");
                ünvan = rs.getString("doktor_ünvan");
                txtdoktor.addItem(ünvan + " " +ad + " " +soyad);
                }
        } catch (SQLException ex) {
            Logger.getLogger(HastaRandevu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    
    
    
    String hasta_isim,hasta_soyisim;
    
    public HastaRandevu() {
        initComponents();
        Connect();
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        txtdoktor.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        dateChooserCombo1.setVisible(false);
        jLabel5.setVisible(false);
        jComboBox1.setVisible(false);
        jButton4.setVisible(false);
    }
    
    public HastaRandevu(String isim,String soyisim){
        this.hasta_isim = isim;
        this.hasta_soyisim = soyisim;
        initComponents();
        Connect();
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        txtdoktor.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        dateChooserCombo1.setVisible(false);
        jLabel5.setVisible(false);
        jComboBox1.setVisible(false);
        jButton4.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpoliklinik = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdoktor = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Randevu Al");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Poliklinik:");

        txtpoliklinik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Algoloji", "Anesteziyoloji ve Reanimasyon", "Beyin ve Sinir Cerrahisi", "Çocuk Cerrahisi", "Çocuk Kalp ve Damar Cerrahisi", "Çocuk Sağlığı ve Hastalıkları", "Dermatoloji", "Endokrinoloji", "Enfeksiyon Hastalıkları", "Fiziksel Tıp ve Reh.(Romatoloji)", "Fiziksel Tıp ve Rehabilitasyon", "Gastroenteroloji", "Genel Cerrahi", "Genel Dahiliye", "Geriatri", "Göğüs Cerrahisi", "Göğüs Hastalıkları", "Göz Hastalıkları", "Hematoloji", "Kadın Hastalıkları ve Doğum", "Kalp ve Damar Cerrahisi", "Kardiyoloji", "Kulak Burun Boğaz Hastalıkları", "Medikal Onkoloji", "Nefroloji", "Nöroloji", "Ortopedi ve Travmatoloji", "Plastik ve Rekonstrüktif Cerrahi", "Romatoloji", "Üroloji" }));

        jButton1.setText("Devam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Doktor:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Tarih:");

        jButton2.setText("Devam");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Devam");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Saat:");

        jButton4.setText("Randevu Al");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08.30", "08.40", "08.50", "09.00", "09.10", "09.20", "09.30", "09.40", "09.50", "10.00", "10.10", "10.20", "10.30", "10.40", "10.50", "11.00", "11.10", "11.20", "11.30", "11.40", "11.50", "13.30", "13.40", "13.50", "14.00", "14.10", "14.20", "14.30", "14.40", "14.50", "15.00", "15.10", "15.20", "15.30", "15.40", "15.50", "16.00", "16.10", "16.20", "16.30", "16.40", "16.50" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtpoliklinik, 0, 245, Short.MAX_VALUE)
                                    .addComponent(txtdoktor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jButton4)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtpoliklinik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtdoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel3.setVisible(true);
        txtdoktor.setVisible(true);
        jButton2.setVisible(true);
        jButton1.setVisible(false);
        LoadDoctor();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setVisible(false);
        jButton3.setVisible(true);
        dateChooserCombo1.setVisible(true);
        jLabel4.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setVisible(false);
        jLabel5.setVisible(true);
        jComboBox1.setVisible(true);
        jButton4.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String tarih = dateChooserCombo1.getText();
        String saat = jComboBox1.getSelectedItem().toString();
        String poliklinik = txtpoliklinik.getSelectedItem().toString();
        
        String date,time,dname,dsurname,tag,pname,psurname;
        int i = 0;
        boolean check1 = false;
        try {
            pst = con.prepareStatement("select * from randevu");
            rs = pst.executeQuery();
            ResultSetMetaData Rsm = rs.getMetaData();
            
            
            while(rs.next())
            {
                date = rs.getString("tarih");
                time = rs.getString("saat");
                dname = rs.getString("doktor_isim");
                dsurname = rs.getString("doktor_soyisim");
                tag = rs.getString("ünvan");
                pname = rs.getString("hasta_isim");
                psurname = rs.getString("hasta_soyisim");
                
                if(date.equals(tarih) && time.equals(saat) && txtdoktor.getSelectedItem().toString().equals(tag + " " +dname + " " +dsurname)){
                   i = 1;
                }
                if(date.equals(tarih) && time.equals(saat) && hasta_isim.equals(pname)&& hasta_soyisim.equals(psurname)){
                   i = 2;
                }
            }
                
        } catch (SQLException ex) {
            Logger.getLogger(DanışmanEkranı.class.getName()).log(Level.SEVERE, null, ex);
        }           
        
        if(i == 1){
            JOptionPane.showMessageDialog(this,"Randevu Dolu, Lütfen Başka Saat veya Tarih Seçiniz");
        }
        else if(i == 2){
            JOptionPane.showMessageDialog(this,"O Tarih ve Saatte Başka Randevunuz Var, Lütfen Başka Saat veya Tarih Seçiniz");
        }
        
        else{
            
        
        try {
            String msql = "INSERT INTO randevu(tarih,saat,hasta_isim,hasta_soyisim,poliklinik,doktor_isim,doktor_soyisim,ünvan)values(?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(msql);
            pst.setString(1, tarih);
            pst.setString(2, saat);
            pst.setString(3, hasta_isim);
            pst.setString(4, hasta_soyisim);
            pst.setString(5, poliklinik);
            pst.setString(6, ad);
            pst.setString(7, soyad);
            pst.setString(8, ünvan);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Randevu Alınmıştır");
            
            this.setVisible(false);
            
            
        
        } catch (SQLException ex) {
            Logger.getLogger(Sayfa1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Hata Burada 3");
            
        }
        
        
        }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaRandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaRandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaRandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaRandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaRandevu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox txtdoktor;
    private javax.swing.JComboBox<String> txtpoliklinik;
    // End of variables declaration//GEN-END:variables
}
